version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - belinda_app/.env
    ports:
      - "5432:5432"

  belinda_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belinda_app
#    env_file:
#      - belinda_app/.env
    networks:
      - default
    ports:
      - "8000:8000"

#  cron:
#    build:
#      context: .
#      dockerfile: cron.Dockerfile
#    volumes:
#      - ./parsers:/app/belinda_app/parsers

volumes:
  data:
    driver: local